use serde::{Deserialize, Serialize};

/// Stable effect IDs. Append new kinds; never reorder published IDs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[repr(u32)]
pub enum FxKind {
    Echo,
    Flanger,
    Gate,
    Reverb,
    Phaser,
    Chorus,
    Tremolo,
    Filter,
    Crush,
    Dist,
    Noise,
    PingPong,
    DubEcho,
    Delay,
    AutoPan,
    EchoOut,
    SpaceEcho,
    LowCutEcho,
    Spiral,
    Helix,
    Mobius,
    Jet,
    Pitch,
    Roll,
    SlipRoll,
    LoopRoll,
    Beatmasher,
    Stutter,
    VinylBrake,
    TapeStop,
    Backspin,
    Space,
    TapeEcho,
    AutoFilter,
    BeatLoop,
    OneShot,
    Transform,
    Reverse,
    Fader,
    Lfo,
    Slicer,
    RingMod,
    Resonator,
    Vocoder,
    Granulizer,
    Spectralizer,
    PatternDelay,
    ReverseDelay,
    Compressor,
    Fuzz,
    Overdrive,
    FreezeVerb,
    AutoSidechain,
    NoiseGate,
    Riser,
    Macro,
    Censor,
    LowPass,
    HighPass,
    BandPass,
    VowelFilter,
    Robot,
    ReverseRoll,
    ReverbOut,
    NoiseSweep,
    GatedNoise,
    NoisePump,
    NoiseFollower,
    PitchDelay,
    MobiusTriangle,
}

impl FxKind {
    pub const ALL: [Self; 70] = [
        Self::Echo,
        Self::Flanger,
        Self::Gate,
        Self::Reverb,
        Self::Phaser,
        Self::Chorus,
        Self::Tremolo,
        Self::Filter,
        Self::Crush,
        Self::Dist,
        Self::Noise,
        Self::PingPong,
        Self::DubEcho,
        Self::Delay,
        Self::AutoPan,
        Self::EchoOut,
        Self::SpaceEcho,
        Self::LowCutEcho,
        Self::Spiral,
        Self::Helix,
        Self::Mobius,
        Self::Jet,
        Self::Pitch,
        Self::Roll,
        Self::SlipRoll,
        Self::LoopRoll,
        Self::Beatmasher,
        Self::Stutter,
        Self::VinylBrake,
        Self::TapeStop,
        Self::Backspin,
        Self::Space,
        Self::TapeEcho,
        Self::AutoFilter,
        Self::BeatLoop,
        Self::OneShot,
        Self::Transform,
        Self::Reverse,
        Self::Fader,
        Self::Lfo,
        Self::Slicer,
        Self::RingMod,
        Self::Resonator,
        Self::Vocoder,
        Self::Granulizer,
        Self::Spectralizer,
        Self::PatternDelay,
        Self::ReverseDelay,
        Self::Compressor,
        Self::Fuzz,
        Self::Overdrive,
        Self::FreezeVerb,
        Self::AutoSidechain,
        Self::NoiseGate,
        Self::Riser,
        Self::Macro,
        Self::Censor,
        Self::LowPass,
        Self::HighPass,
        Self::BandPass,
        Self::VowelFilter,
        Self::Robot,
        Self::ReverseRoll,
        Self::ReverbOut,
        Self::NoiseSweep,
        Self::GatedNoise,
        Self::NoisePump,
        Self::NoiseFollower,
        Self::PitchDelay,
        Self::MobiusTriangle,
    ];
    pub fn from_id(id: u32) -> Self {
        Self::ALL.get(id as usize).copied().unwrap_or(Self::Echo)
    }
    pub fn parse(name: &str) -> Option<Self> {
        match name {
            "sweep" => Some(Self::Filter),
            "trans" => Some(Self::Gate),
            "bitcrusher" => Some(Self::Crush),
            "distortion" => Some(Self::Dist),
            "pingpong" | "ping-pong-delay" => Some(Self::PingPong),
            "vinyl-stop" | "vinyl_stop" | "brake" => Some(Self::VinylBrake),
            "ringmod" | "ringmodulator" => Some(Self::RingMod),
            "rev_roll" => Some(Self::ReverseRoll),
            "enigma_jet" => Some(Self::Jet),
            "freezeverb" => Some(Self::FreezeVerb),
            "sidechain" => Some(Self::AutoSidechain),
            "filtered-delay" => Some(Self::LowCutEcho),
            "polyrhythmic-delay" => Some(Self::PatternDelay),
            _ => Self::ALL
                .into_iter()
                .find(|k| k.as_str() == name || k.as_str().replace('_', "-") == name),
        }
    }
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Echo => "echo",
            Self::Flanger => "flanger",
            Self::Gate => "gate",
            Self::Reverb => "reverb",
            Self::Phaser => "phaser",
            Self::Chorus => "chorus",
            Self::Tremolo => "tremolo",
            Self::Filter => "filter",
            Self::Crush => "crush",
            Self::Dist => "dist",
            Self::Noise => "noise",
            Self::PingPong => "ping_pong",
            Self::DubEcho => "dub_echo",
            Self::Delay => "delay",
            Self::AutoPan => "auto_pan",
            Self::EchoOut => "echo_out",
            Self::SpaceEcho => "space_echo",
            Self::LowCutEcho => "low_cut_echo",
            Self::Spiral => "spiral",
            Self::Helix => "helix",
            Self::Mobius => "mobius",
            Self::Jet => "jet",
            Self::Pitch => "pitch",
            Self::Roll => "roll",
            Self::SlipRoll => "slip_roll",
            Self::LoopRoll => "loop_roll",
            Self::Beatmasher => "beatmasher",
            Self::Stutter => "stutter",
            Self::VinylBrake => "vinyl_brake",
            Self::TapeStop => "tape_stop",
            Self::Backspin => "backspin",
            Self::Space => "space",
            Self::TapeEcho => "tape_echo",
            Self::AutoFilter => "auto_filter",
            Self::BeatLoop => "beat_loop",
            Self::OneShot => "one_shot",
            Self::Transform => "transform",
            Self::Reverse => "reverse",
            Self::Fader => "fader",
            Self::Lfo => "lfo",
            Self::Slicer => "slicer",
            Self::RingMod => "ring_mod",
            Self::Resonator => "resonator",
            Self::Vocoder => "vocoder",
            Self::Granulizer => "granulizer",
            Self::Spectralizer => "spectralizer",
            Self::PatternDelay => "pattern_delay",
            Self::ReverseDelay => "reverse_delay",
            Self::Compressor => "compressor",
            Self::Fuzz => "fuzz",
            Self::Overdrive => "overdrive",
            Self::FreezeVerb => "freeze_verb",
            Self::AutoSidechain => "auto_sidechain",
            Self::NoiseGate => "noise_gate",
            Self::Riser => "riser",
            Self::Macro => "macro",
            Self::Censor => "censor",
            Self::LowPass => "low_pass",
            Self::HighPass => "high_pass",
            Self::BandPass => "band_pass",
            Self::VowelFilter => "vowel_filter",
            Self::Robot => "robot",
            Self::ReverseRoll => "reverse_roll",
            Self::ReverbOut => "reverb_out",
            Self::NoiseSweep => "noise_sweep",
            Self::GatedNoise => "gated_noise",
            Self::NoisePump => "noise_pump",
            Self::NoiseFollower => "noise_follower",
            Self::PitchDelay => "pitch_delay",
            Self::MobiusTriangle => "mobius_triangle",
        }
    }
}
