[package]
name = "mixless-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Native development and packaging tools"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
mixless-protocol = { workspace = true }
sha2 = "0.10"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
zip = { version = "2.4", default-features = false, features = ["deflate"] }
tempfile = "3"

[dev-dependencies]
tempfile = "3"
