[package]
name = "mixless-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Realtime dual-deck mixer. No analysis, no SQL."

[dependencies]
mixless-protocol = { workspace = true }
cpal = { workspace = true }
rtrb = { workspace = true }
symphonia = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
ebur128 = "0.1.10"
hound = "3"

[build-dependencies]
cc = "1"

[dev-dependencies]
tempfile = "3"
mixless-mixplan = { workspace = true }
